<?php

return [
    'team' => 'Team',
    't1' => 'The Issue Monitoring Team',
    'p1' => 'is the founder of Issue Monitoring, a project that reflects his professional experience of over ten years in advocacy, public affairs and consultancy, working both with private companies and with nonprofit organizations. Throughout his career, he has been part of various technical assistance programs for the Ministry of Economy, Ministry of Labor, Ministry of European Funds, as well as other institutions of the central public administration.',
    'p2' => 'Currently he works as an Associate Consultant with Graffiti PR, being involved in several public affairs and advocacy campaigns. He previously worked as Public Affairs Consultant with Șerban & Musneci Associates. Starting with 2003 he has been coordinating, along with the Civil Society Development Foundation, the most important advocacy campaigns that aim at amending the legal and fiscal framework for NGOs in Romania.',
    'p3' => 'Octavian Rusu is a graduate of the University of Bucharest, having received his BA from the Faculty of Law and his MA in Strategic Management and Social Development from the Faculty of Sociology and Social Work. Since 2006 he has been a permanent collaborator with the International Center for Nonprofit Law, being part of the team that elaborated the annual report concerning the legislative framework of NGOs in Romania.',
    'p4' => 'has over five years of experience in media, having worked as an editor both for the Monitoring Department of Mediafax Press Agency, and for the online platform of B1TV news channel. She also has extensive experience in specialized translations. Alexandra is a graduate of the Faculty of Letters, University of Bucharest, and received her first MA in Literary Theory, while her second MA in Comparative Historical Studies was awarded to her by the Central European University - CEU Budapest. Throughout her professional career, she participated in several workshops and specialized training programs in the field of public policy. Currently, she coordinates the activity of CMPP\'s Monitoring team and is one of the editors of the specialized reports and public policy analyses offered by CMPP.',
    'monitoring_team' => 'The monitoring team',
    'monitoring_team_phrase' => 'consists of university graduates in Political Sciences, Law, and History, whose professional experience and training offer them the expertise required for writing specialized reports and public policy analyses. Throughout their professional careers, the members of the monitoring team have participated in several trainings and specialized study programs in the field of public policy, or have volunteered to carry out projects developed by several NGOs, associations and foundations. The added value that the members of the monitoring team bring to the services offered by Issue Monitoring is also reflected in their participation in the debate sessions held by the specialized Committees of the central public administration bodies - the Chamber of Deputies, the Senate, Ministries, etc. Their presence during the debates helps promptly notify customers of all amendments brought to the monitored initiatives, in the process of passing a bill.',
];
