<?php

return [
    'team' => 'Echipa',
    't1' => 'Echipa Issue Monitoring',
    'p1' => 'este fondatorul Issue Monitoring, proiect care exprimă experiența sa profesională de peste 10 ani în servicii de advocacy, public affairs și consultanță pentru companii din diverse domenii de activitate și organizații neguvernamentale de top din România. De-a lungul activității a fost implicat în diverse programe de asistență tehnică pentru Ministerul Economie, Ministerul Muncii, Ministerul Fondurilor Europene și alte autorități  publice centrale.',
    'p2' => 'În prezent este consultant asociat al companiei Graffiti PR, fiind implicat în derularea unor campanii de public affairs și advocacy pentru diverși clienți. Anterior a lucrat ca și consultant de public affairs pentru compania Șerban & Musneci Associates. Începând cu anul 2003 a coordonat alături de Fundația pentru Dezvoltarea Societății Civile cele mai importante campanii de advocacy de modificare legislativă a cadrului juridic și fiscal pentru organizațiile neguvernamentale din România.',
    'p3' => 'Octavian Rusu este absolvent al Facultății de Drept și a urmat cursuri masterale în Management strategic și dezvoltare socială în cadrul Universității din București. Este colaborator permanent al International Center for Nonprofit Law începând din anul 2006, participând la elaborarea raportului anual privind cadrul legislativ al sectorului ONG din România.',
    'p4' => 'cu o experiență de peste cinci ani în domeniul media, a activat ca redactor atât în departamentul de Monitorizare presă al agenției Mediafax, cât și în redacția de știri a site-ului B1.ro.  De asemenea, are o bogată experiență în traduceri de specialitate. A absolvit Facultatea de Litere din cadrul Universității din București, urmând apoi studii masterale în Teoria Literaturii, precum și în Istorie comparativă în cadrul Central European University - CEU Budapesta. De-a lungul activității sale profesionale, a participat la training-uri și cursuri de perfecționare în domeniul politicilor publice. În prezent coordonează activitatea echipei de monitorizare din cadrul Centrului pentru Monitorizarea Politicilor Publice și este unul dintre redactorii rapoartelor specializate și a analizelor de politici publice oferite de CMPP.',
    'monitoring_team' => 'Echipa de monitorizare',
    'monitoring_team_phrase' => 'are în componență absolvenți ai facultăților de Științe politice, Drept sau Istorie, a căror formare profesională și experiență le oferă acestora expertiza necesară redactării rapoartelor specializate și a analizelor de politici publice. La acestea se adaugă și numeroase cursuri de perfecționare și training-uri în domeniul politicilor publice, urmate în cadrul proiectelor CMPP. De-a lungul timpului, membrii echipei au fost implicați în acțiuni de voluntariat în cadrul mai multor ONG-uri, asociații sau fundații. Valoarea adăugată pe care membrii echipei o aduc serviciilor Issue Monitoring se regăsește și în participarea acestora în cadrul ședințelor comisiilor de specialitate ale autorităților de reglementare – Camera Deputaților, Senat, ministere etc. –, înștiințând astfel în timp real clienții de toate modificările aduse inițiativelor legislative monitorizate, în procesul acestora de adoptare.',
];
